# 产品名称
spring:
  application:
    name: yinglibao
    # 连接数据库
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yinglibao?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 208119

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # redis配置
  redis:
    host: localhost
    port: 6379
    password: 208119
# 配置mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/**/*.xml
# 端口和访问路径
server:
  port: 8088
  servlet:
    context-path: /api

sms:
  url: https://way.jd.com/chuangxin/dxjk
  appkey: 3680fa919b771148da626bbcbd459475
  reg-text: 【动力金融】你的注册验证码是%s，请注意保护，3分钟有效
  login-text: 【动力金融】你的登录验证码是%s，请注意保护，10分钟有效

secret:
  salt: B%RN&F%b%jKz8v37E3k%buE@Z9$%y#ED