# 产品名称
spring:
  application:
    name: yinglibao
    # 连接数据库
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yinglibao?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 208119

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
# 配置mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/**/*.xml
# 端口和访问路径
server:
  port: 8088
  servlet:
    context-path: /api
